variables:
  RELEASE_DOCKER_REGISTRY: quay.io
  RELEASE_DOCKER_REPOSITORY: dotmesh

stages:
  - deploy

deploy_docker_image:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD $RELEASE_DOCKER_REGISTRY
    - docker build -t quay.io/dotmesh/nbdime:$CI_COMMIT_SHA .
    - docker push quay.io/dotmesh/nbdime:$CI_COMMIT_SHA