variables:
  RELEASE_DOCKER_REGISTRY: quay.io
  RELEASE_DOCKER_REPOSITORY: dotmesh

stages:
  - deploy

deploy_docker_image:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - docker build -t quay.io/dotmesh/nbdime:$CI_COMMIT_SHA .
    - docker login -u $QUAY_USERNAME -p $QUAY_PASSWORD quay.io
    - docker push quay.io/dotmesh/nbdime/$CI_COMMIT_SHA