variables:
  RELEASE_DOCKER_REGISTRY: quay.io
  RELEASE_DOCKER_REPOSITORY: dotmesh
  CI_DOCKER_TAG: $CI_COMMIT_SHA
  CI_DOCKER_PYTHON_IMAGE: $RELEASE_DOCKER_REGISTRY/$RELEASE_DOCKER_REPOSITORY/dotscience-python3:$CI_COMMIT_SHA

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - ubuntu-bionic
    - fast
  script:
    - ./test.sh

deploy_docker_image:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD $RELEASE_DOCKER_REGISTRY
    - ./shipit-docker.sh

deploy_docker_image_latest:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD $RELEASE_DOCKER_REGISTRY
    - CI_DOCKER_PYTHON_IMAGE=$RELEASE_DOCKER_REGISTRY/$RELEASE_DOCKER_REPOSITORY/dotscience-python3:latest ./shipit-docker.sh
  when: manual

# Needs PYPI_USER and PYPI_PASSWORD set; and optionally PYPI_REPO if we're using test pypi
deploy_pypi:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - ./shipit-pypi.sh -u $PYPI_USER -p $PYPI_PASSWORD
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD $RELEASE_DOCKER_REGISTRY
    - CI_DOCKER_PYTHON_IMAGE=$RELEASE_DOCKER_REGISTRY/$RELEASE_DOCKER_REPOSITORY/dotscience-python3:$CI_COMMIT_TAG ./shipit-docker.sh
    - curl -X POST -F "token=$CI_JOB_TOKEN" -F "ref=master" -F "variables[DOTSCIENCE_TAG]=$CI_COMMIT_TAG" https://gitlab.dotmesh.com/api/v4/projects/dotmesh%2Fjupyterlab-tensorflow-sync/trigger/pipeline
  only:
    refs:
       - tags
    variables:
       - $CI_COMMIT_TAG =~ /[0-9]+\.[0-9]+\.[0-9]+/
