variables:
  RELEASE_DOCKER_REGISTRY: quay.io
  RELEASE_DOCKER_REPOSITORY: dotmesh

stages:
  - deploy

deploy_docker_image:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - ./release.sh $CI_COMMIT_SHA